services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms-data-jpa
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    name: postgres_volumes